package com.kobe.dinger.model;

public enum NotificationEvent {
    INNING_CHANGE,
    HALF_INNING_CHANGE,
    SCORE_CHANGE,
    GAME_END,
    WEEKLY_SCHEDULE,
    GAME_STARTING,
    GAME_DAY_REMINDER,
    END_GAME_STANDINGS,
    END_DAY_STANDINGS,
    STARTING_PITCHER,
    END_INNING_PITCHER_STATS,
    PITCHER_CHANGE,
    GAME_DAY_LINEUP,
    LEAD_CHANGE,
    STARTING_PITCHER_CHANGE
}
