package com.kobe.dinger.model;

public enum NotificationEvent {
    INNING_CHANGE,
    HALF_INNING_CHANGE,
    SCORE_CHANGE,
    HOMERUN,
    HIT,
    GAME_END,
    WEEKLY_SCHEDULE,
    GAME_STARTING,
    GAME_DAY_REMINDER,
    PROBABLE_PITCHER,
    END_GAME_STANDINGS,
    END_DAY_STANDINGS,
    GAMES_BEHIND_FIRST,
    GAME_BEHIND_WILDCARD,
    STARTING_PITCHER,
    END_INNING_PITCHER_STATS,
    PITCHER_CHANGE
}
