services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: dinger
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
