const styles = {
    container: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100vh',
        backgroundColor: '#737373',
        fontFamily: "'Quicksand', sans-serif",
    },
    logoWrapper: {
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    swingImage: {
        position: 'absolute',
        width: '110px',
        opacity: 0.9,
        pointerEvents: 'none',
        top: '-92px',
    },
    title: {
        fontSize: '3rem',
        fontWeight: '400',
        color: '#ffffff',
        fontFamily: "'Parkinsans', sans-serif",
        margin: '0',
        lineHeight: '1.4',
        textShadow: '0 2px 12px rgba(0, 0, 0, 0.4)',
        position: 'relative',
    },
    subtitle: {
        fontSize: '0.95rem',
        fontWeight: '600',
        color: '#ffffff',
        marginTop: '0.75rem',
        marginBottom: '1.75rem',
        textShadow: '0 2px 12px rgba(0, 0, 0, 0.4)',
    },
    buttonRow: {
        display: 'flex',
        gap: '0.75rem',
    },
    button: {
        padding: '0.5rem 1.5rem',
        fontSize: '0.85rem',
        fontFamily: "'Quicksand', sans-serif",
        fontWeight: '600',
        borderRadius: '8px',
        border: 'none',
        cursor: 'pointer',
        backgroundColor: '#ffffff',
        color: '#0f0f0f',
    },
    card: {
        backgroundColor: '#626262',
        borderRadius: '12px',
        padding: '2rem',
        display: 'flex',
        flexDirection: 'column',
        gap: '0.75rem',
        width: '320px',
        boxShadow: '0 4px 20px rgba(0, 0, 0, 0.3)',
    },
    cardTitle: {
        fontSize: '1.5rem',
        fontWeight: '600',
        color: '#ffffff',
        fontFamily: "'Parkinsans', sans-serif",
        marginBottom: '0.25rem',
        textAlign: 'center',
    },
    input: {
        padding: '0.6rem 0.9rem',
        fontSize: '0.9rem',
        fontFamily: "'Quicksand', sans-serif",
        borderRadius: '8px',
        border: 'none',
        outline: 'none',
        backgroundColor: '#737373',
        color: '#ffffff',
    },
    errorText: {
        color: '#ff6b6b',
        fontSize: '0.8rem',
        textAlign: 'center',
    },
    linkText: {
        color: '#dddddd',
        fontSize: '0.8rem',
        textAlign: 'center',
        cursor: 'pointer',
        marginTop: '0.25rem',
    },
}

export default styles
