const styles = {
    container: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        height: '100vh',
        backgroundColor: '#4a4a4a',
        fontFamily: "'Zalando Sans Expanded', sans-serif",
    },
    logoWrapper: {
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
    },
    swingImage: {
        width: '215px',
        position: 'absolute',
        left: '-85px',
        top: '48%',
        transform: 'translateY(-50%)',
        zIndex: 0,
        pointerEvents: 'none',
    },
    title: {
        fontSize: '3.6rem',
        fontWeight: '300',
        color: '#ffffff',
        fontFamily: "'Zalando Sans Expanded', sans-serif",
        margin: '0',
        lineHeight: '1.4',
        textShadow: '0 0 30px rgba(255, 255, 255, 0.25), 0 0 60px rgba(255, 255, 255, 0.15), 0 2px 16px rgba(0, 0, 0, 0.6), 0 4px 30px rgba(0, 0, 0, 0.35)',
        position: 'relative',
        zIndex: 1,
        transform: 'translateY(12px)',
    },
    subtitle: {
        fontSize: '0.95rem',
        fontWeight: '600',
        color: '#ffffff',
        marginTop: '0.75rem',
        marginBottom: '1.75rem',
        textShadow: '0 2px 12px rgba(0, 0, 0, 0.4)',
    },
    buttonRow: {
        display: 'flex',
        gap: '3rem',
        marginTop: '3.5rem',
    },
    navLink: {
        color: '#c1bba0',
        fontSize: '1.6rem',
        fontFamily: "'Zalando Sans Expanded', sans-serif",
        fontWeight: '400',
        cursor: 'pointer',
        background: 'none',
        border: 'none',
        padding: '0',
        letterSpacing: '0.04em',
        textShadow: '0 0 16px rgba(60, 57, 45, 1)',
    },
    button: {
        padding: '0.5rem 1.5rem',
        fontSize: '0.85rem',
        fontFamily: "'Zalando Sans Expanded', sans-serif",
        fontWeight: '600',
        borderRadius: '8px',
        border: 'none',
        cursor: 'pointer',
        backgroundColor: '#ffffff',
        color: '#0f0f0f',
    },
    card: {
        backgroundColor: '#626262',
        borderRadius: '12px',
        padding: '2rem',
        display: 'flex',
        flexDirection: 'column',
        gap: '0.75rem',
        width: '320px',
        boxShadow: '0 4px 20px rgba(0, 0, 0, 0.3)',
    },
    cardTitle: {
        fontSize: '1.5rem',
        fontWeight: '600',
        color: '#ffffff',
        fontFamily: "'Zalando Sans Expanded', sans-serif",
        marginBottom: '0.25rem',
        textAlign: 'center',
    },
    input: {
        padding: '0.6rem 0.9rem',
        fontSize: '0.9rem',
        fontFamily: "'Zalando Sans Expanded', sans-serif",
        borderRadius: '8px',
        border: 'none',
        outline: 'none',
        backgroundColor: '#4a4a4a',
        color: '#ffffff',
    },
    scrollIndicator: {
        position: 'absolute',
        bottom: '2rem',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '0.3rem',
        animation: 'bounce 1.8s ease-in-out infinite',
        opacity: 0.5,
    },
    scrollChevron: {
        width: '24px',
        height: '24px',
        borderRight: '2px solid #c1bba0',
        borderBottom: '2px solid #c1bba0',
        transform: 'rotate(45deg)',
    },
    errorText: {
        color: '#ff6b6b',
        fontSize: '0.8rem',
        textAlign: 'center',
    },
    linkText: {
        color: '#dddddd',
        fontSize: '0.8rem',
        textAlign: 'center',
        cursor: 'pointer',
        marginTop: '0.25rem',
    },
}

export default styles
